pipeline {
    agent any

    stages {

        // stage('Code Quality Scan') {
        //     dir('./webgoat'){
        //         sh "mvn sonar:sonar -Dsonar.host.url=http://localhost:9000"
        //     }
        // }

        stage('Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore clean package'
            }
            post {
                success {
                    echo 'Now archiving...'
                    archiveArtifacts artifacts: "**/target/*.war"
                }
            }
        }

        stage('Nexus IQ Scan'){
            steps {
                script{
                def policyEvaluation = nexusPolicyEvaluation failBuildOnNetworkError: false, iqApplication: 'webgoat-server-side', iqStage: 'build', jobCredentialsId: ''
                }
                echo "====================================="
                echo 'IQ scan results'
                echo "-------------------------------------"
                sh 'echo ${policyEvaluation}'
                echo "====================================="
            }
        }    
    }
}



https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=101534874&redirect_uri=http%3A%2F%2Flocalhost%3A9005
